controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fishbot_mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

fishbot_mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: left_front_wheel_joint
    front_right_wheel_command_joint_name: right_front_wheel_joint
    rear_left_wheel_command_joint_name: left_rear_wheel_joint
    rear_right_wheel_command_joint_name: right_rear_wheel_joint
    front_left_wheel_state_joint_name: left_front_wheel_joint
    front_right_wheel_state_joint_name: right_front_wheel_joint
    rear_left_wheel_state_joint_name: left_rear_wheel_joint
    rear_right_wheel_state_joint_name: right_rear_wheel_joint
    kinematics:
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.36
    base_frame_id: base_footprint
    odom_frame_id: odom
    use_stamped_vel: false
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
